### ISSUE TITLE
Error when running software

### ISSUE THREAD

**Issue by ghost** [ajchili/ChosunTruck#2]
The error that is happening is:
`OpenCV Error: Assertion failed (src.checkVector(2, CV_32F) == 4 && dst.checkVect
or(2, CV_32F) == 4) in cv::getPerspectiveTransform, file D:\michael.mueller\Sons
tiges\Temp\ocv31\opencv_sources\modules\imgproc\src\imgwarp.cpp, line 6353`
I have Windows 7 64-bit. I use ETS2 in 64-bit mode.

**Comment by zappybiby** [comment]
Yep, I get the same thing when running in debug mode. Right now I'm using Release mode and it works fine.

I've notified the devs about this but not sure why it's only happening in debug. That error usually means theres a problem converting Mat type.

**Comment by ghost** [comment]
Could you send me the file because I can't install CUDA on my machine as it doesn't want to install it. Without CUDA I can't make my own build of the project.

**Comment by zappybiby** [comment]
https://www.nuget.org/packages/opencvcuda-release/
https://www.nuget.org/packages/opencvcuda-debug/

These are links to pre-built OpenCV CUDA libraries. This will give you all of the #include libraries needed.
