### ISSUE TITLE
[TensorBox] Need to grab Shared Memory in Windows

### ISSUE THREAD

**Issue by zappybiby** [ajchili/ChosunTruck#3]
https://github.com/ajchili/ChosunTruck/blob/master/tensorbox/Car_detection.py#L54 will not work because Windows does not have sysv_ipc module. Need to find another way to grab memory.

**Comment by zappybiby** [comment]
@chi3236 Any ideas? I think we could use CreateFileMapping() with OpenFileMapping() for emulating the capture of shared memory as we do in linux.

(FYI: I am in the process of converting our program to work with TensorBox on Windows)

**Comment by chi3236** [comment]
Maybe we can use sysv_ipc module with Cygwin in Windows.... but let's not do that Cygwin sucks...

I checked [this page](https://msdn.microsoft.com/en-us/library/aa366537(VS.85).aspx) and seems like we can use that method, but looks more complicated than in Linux. I will search other methods which are simpler than MSDN method.
